module.exports={
    tableName:'orders',
    attributes:{
        type:{
            type:'string',
            enum:["scheduled", "asap"]
        },
        items:{
            type:'array'
        },
        userId:{
            type:'string'   
        },        
        contactPhone:{
            type:'string'
        },
        userComments:{
            type:'string'
        },
        adminComments:{
            type:'string'
        },        
        totalAmount:{
            type:'float'
        },
        actualAmount:{
            type:'float'
        },
        paymentType:{
            type:'string',
            enum:["creditcard", "swyftdebit", "cash"]
        },
        isDelivered:{
            type:'boolean',
            defaultsTo:false
        },
        deliveredAt:{
            type:'datetime'
        },
        deliveryTime:{
            type:'datetime'
        },
        deliveryId:{
            type:'string'
        },
        deliveryLocation:{
            type:'string'
        },
        couponId:{
            type:'string'
        },
        tokenId:{
            type:'string'
        },
        disabled:{
            type:'boolean',
            defaultsTo:false
        }
    },
}