module.exports={
    tableName:'restaurants',
    attributes:{
        name:{
            type:'string'
        },
        title:{
            type:'string'
        },  
        unavailable:{
            type:'boolean',
            defaultsTo:true
        }
    },
}