module.exports={
    tableName:'system',
    attributes:{
        suppressOrders:{
            type:'boolean',
            defaultsTo:false
        },
        suppressSignUps:{
            type:'boolean',
            defaultsTo:false
        },
        suppressSystem:{
            type:'boolean',
            defaultsTo:false
        },
        allowASAPorders:{
            type:'boolean',
            defaultsTo:false
        }
    },
}